"""HTTP API for TV5's UI (WP13) to consume TV4's Query Router / Fusion /
KIS / VQA / TRAKE pipelines interactively, one query at a time.

This module deliberately contains NO retrieval/fusion/alignment logic of its
own -- it only adapts the existing `kis_pipeline` / `trake_pipeline` /
`wp11_vqa` functions (already used by `cli.py`) to HTTP, the same way TV1's
wp06_api_server.py and TV3's backend/app/main.py wrap their own pipelines.

Run:
    TV4_CONFIG=configs/default.yaml uvicorn tv4.api:app --host 127.0.0.1 --port 8200

Fixture mode (for TV5 to build the UI before TV1/TV2/TV3 are all live):
    TV4_FIXTURE_MODE=1 uvicorn tv4.api:app --host 127.0.0.1 --port 8200
Fixture mode needs no config, no TV1/TV2/TV3 running, and no GPU -- every
endpoint returns the canned payloads in `fixtures.py`, contract-accurate.

Docs auto-generated by FastAPI at /docs (OpenAPI/Swagger) and /redoc double
as the schema hand-off TV5 needs -- no separate schema doc to keep in sync.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from . import fixtures
from .cli import _load_config, build_services
from .kis_pipeline import KisServices, run_kis_query
from .trake_pipeline import run_trake_query
from .wp11_vqa import RuleBasedFallbackEngine, answer_query

FIXTURE_MODE = os.environ.get("TV4_FIXTURE_MODE", "0") == "1"
CONFIG_PATH = os.environ.get("TV4_CONFIG", "configs/default.yaml")
CORS_ORIGINS = [o.strip() for o in os.environ.get("TV4_CORS_ORIGINS", "*").split(",") if o.strip()]

_services: KisServices | None = None


class TV4ConfigError(RuntimeError):
    pass


def _get_services() -> KisServices:
    global _services
    if _services is None:
        try:
            config = _load_config(CONFIG_PATH)
            config["_config_dir"] = str(Path(CONFIG_PATH).parent)
            _services = build_services(config)
        except Exception as exc:
            raise TV4ConfigError(f"failed to load config/services from {CONFIG_PATH}: {exc}") from exc
    return _services


app = FastAPI(
    title="TV4 — Query Router / Fusion / KIS / VQA / TRAKE",
    version="0.1.0",
    description="WP07, WP10, WP11, WP12 for AIC 2026. See /docs for the full "
                 "SearchCandidate / VqaResult / TrakeHypothesis schema.",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_methods=["*"],
    allow_headers=["*"],
)


class KisRequest(BaseModel):
    query_text: str
    query_id: str | None = None
    top_k: int = Field(default=100, ge=1, le=100)


class VqaRequest(BaseModel):
    query_text: str
    question: str
    query_id: str | None = None
    top_k: int = Field(default=100, ge=1, le=100)
    top_k_answers: int = Field(default=5, ge=1, le=20, description="How many top candidates to actually run the answer engine on (expensive per-call).")


class TrakeRequest(BaseModel):
    query_text: str
    events: list[str] | None = None
    query_id: str | None = None
    strategy: str = Field(default="dp", pattern="^(dp|greedy)$")


@app.get("/health")
def health() -> dict[str, Any]:
    if FIXTURE_MODE:
        return {"status": "ok", "mode": "fixture"}
    try:
        services = _get_services()
    except TV4ConfigError as exc:
        return {"status": "degraded", "mode": "live", "error": str(exc)}
    return {"status": "ok", "mode": "live", "preprocess_run_id": services.preprocess_run_id}


@app.post("/kis/search")
def kis_search(req: KisRequest) -> dict[str, Any]:
    if FIXTURE_MODE:
        return fixtures.KIS_RESPONSE
    try:
        services = _get_services()
        ranked = run_kis_query(req.query_text, services, query_id=req.query_id, top_k=req.top_k)
    except TV4ConfigError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"KIS pipeline failed: {exc}") from exc
    query_id = ranked[0].query_id if ranked else (req.query_id or "kis-query")
    return {"query_id": query_id, "candidates": [c.to_json() for c in ranked]}


@app.post("/vqa/answer")
def vqa_answer(req: VqaRequest) -> dict[str, Any]:
    if FIXTURE_MODE:
        return fixtures.VQA_RESPONSE
    try:
        services = _get_services()
        ranked = run_kis_query(req.query_text, services, query_id=req.query_id, top_k=req.top_k)
    except TV4ConfigError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"KIS pipeline failed: {exc}") from exc
    if not ranked:
        return {"query_id": req.query_id or "vqa-query", "results": []}
    engine = RuleBasedFallbackEngine()  # TODO(TV4): swap for a real VLM/LLM AnswerEngine before demo
    results = [
        answer_query(c, req.question, services.tv1, services.tv3, engine)
        for c in ranked[: req.top_k_answers]
    ]
    return {
        "query_id": ranked[0].query_id,
        "results": [
            {
                "rank": r.candidate.rank,
                "video_id": r.candidate.video_id,
                "frame_id": r.candidate.frame_id,
                "timestamp_ms": r.candidate.timestamp_ms,
                "confidence": r.candidate.confidence,
                "answer": r.answer,
                "verified": r.verified,
                "manual_review": r.manual_fallback,
                "evidence": r.evidence.to_json(),
            }
            for r in results
        ],
    }


@app.post("/trake/align")
def trake_align(req: TrakeRequest) -> dict[str, Any]:
    if FIXTURE_MODE:
        return fixtures.TRAKE_RESPONSE
    try:
        services = _get_services()
        hyp = run_trake_query(
            req.query_text, services, events=req.events, query_id=req.query_id, strategy=req.strategy
        )
    except TV4ConfigError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"TRAKE pipeline failed: {exc}") from exc
    if hyp is None:
        return {"query_id": req.query_id or "trake-query", "result": None, "message": "no monotonic alignment found"}
    return {
        "query_id": hyp.query_id,
        "result": {
            "video_id": hyp.video_id,
            "frame_ids": list(hyp.frame_ids),
            "event_scores": list(hyp.event_scores),
            "aggregate_score": hyp.aggregate_score,
            "preprocess_run_id": hyp.preprocess_run_id,
        },
    }